# SPDX-License-Identifier: MIT
version: 2
project_name: kubectl-dpm
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/bavarianbidi/kubectl-dpm/pkg/command.appVersion={{.Version}}
      - -X github.com/bavarianbidi/kubectl-dpm/pkg/command.buildDate={{.Date}}
      - -X github.com/bavarianbidi/kubectl-dpm/pkg/command.gitCommit={{.Commit}}
    main: ./cmd/kubectl-dpm.go

archives:
  - id: "tar ball"
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
  - id: "binary"
    format: binary

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  use: github
  groups:
    - title: "✨ Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "🐛 Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "📚 Documentation"
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "🌱 Others"
      order: 999
  filters:
    exclude:
      - "^test:"
release:
  github:
    owner: bavarianbidi
    name: kubectl-dpm
  prerelease: auto
  extra_files:
    - glob: tmp/kubectl-dpm.bom.spdx
