# SPDX-License-Identifier: MIT

name: release

on:
  push:
    # run only against tags
    tags:
      - 'v*'

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'

      - name: release
        run: make release
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}

      - name: Update new version in krew-index
        uses: rajatjindal/krew-release-bot@v0.0.47
      
      # attest archives
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: "dist/*.tar.gz"
      
      # attest SBOM
      - name: Generate SBOM attestation
        uses: actions/attest-sbom@v2
        with:
          subject-path: "dist/*.tar.gz"
          sbom-path: "tmp/kubectl-dpm.bom.spdx"