# SPDX-License-Identifier: MIT

name: release

on:
  push:
    # run only against tags
    tags:
      - "v*"

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e #v7.0.0
        with:
          go-version-file: go.mod

      - name: release
        run: make release
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}

      - name: Update new version in krew-index
        uses: rajatjindal/krew-release-bot@c970b8a8f6dbc2f2285a26e3ae160903b87002c3 #v0.0.51

      # attest archives
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@0f67c3f4856b2e3261c31976d6725780e5e4c373 #v4.1.1
        with:
          subject-path: "dist/*.tar.gz"

      # attest SBOM
      - name: Generate SBOM attestation
        uses: actions/attest-sbom@c604332985a26aa8cf1bdc465b92731239ec6b9e #v4.1.0
        with:
          subject-path: "dist/*.tar.gz"
          sbom-path: "tmp/kubectl-dpm.bom.spdx"
